### ISSUE TITLE
Simple contract kills sandbox on debug. (Warning need to be added)

### ISSUE THREAD

**Issue by DaveAppleton** [ether-camp/ethereum-sandbox#51]
```
pragma solidity ^0.4.0;

contract babyFace {
    address[]  arrayOfL;
    uint256    x;
    
    function pusheen() {
        x = 1;
        arrayOfL.push(this);
    }
    
    event lp(address);
    
    function popeen() {
        lp(arrayOfL[0]);
    }
    
    function len() constant returns (uint256) {
        return arrayOfL.length;
    }
}
```
Place a breakpoint at `x=1` in `pusheen`

![image](https://cloud.githubusercontent.com/assets/1858302/23183097/d643def2-f8b5-11e6-886b-0e8dc86370e8.png)

Debug `pusheen`

![image](https://cloud.githubusercontent.com/assets/1858302/23183289/81a2f508-f8b6-11e6-9290-b31e9d851ecf.png)

Lo! The sandbox has stopped

**Comment by DaveAppleton** [comment]
Changing to this (i.e. removing the arrays) allows the breakpoint to be hit.
```
pragma solidity ^0.4.0;

contract babyFace {
   
   
    uint256    x;
    
    function pusheen() {
        x = 1;
    //    arrayOfL.push(this);
    }
    
    event lp(address);
    
    // function popeen() {
    //     lp(arrayOfL[0]);
    // }
    
    // function len() constant returns (uint256) {
    //     return arrayOfL.length;
    // }

}
```

**Comment by asinyagin** [comment]
@DaveAppleton that happens because you have
```
      "0x17956ba5f4291844bc25aedb27e69bc11b5bda39": {
        "balance": 0,
        "deploy": {
          "source": "_pre/feeTables.sol",
          "contract": "feeTables"
        }
      },
```
in your ethereum.json. The contract sets some storage vars on `0x17956ba5f4291844bc25aedb27e69bc11b5bda39` account. Then IDE sends contract from `0xdedb49385ad5b94a16f236a6890cf9e0b1e30392` and it's deployed on the same address `0x17956ba5f4291844bc25aedb27e69bc11b5bda39`. That's why your array have length `0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba`.

I'm not sure if we should some error here. Maybe some warning.

**Comment by romanman** [comment]
duplicate #54
